### ISSUE TITLE
Change exp to a peerDependency

### ISSUE THREAD

**Issue by motiz88** [FormidableLabs/appr#23]
`appr`'s current behaviour is to [prefer `<app>/node_modules/exp`](https://github.com/FormidableLabs/appr/blob/a2520e3d97f08356b950fc29558dc4c496157362/index.js#L8) over `<app>/node_modules/appr/node_modules/exp` - a duplication that exists if the app has a newer or incompatible version of `exp` as a dependency.

This is useful behaviour - e.g. to synchronise the version of `exp` between `appr` and any custom CI scripts used by the app. Moving `exp` to `peerDependencies` would simply codify it and make it explicit.

**Comment by jevakallio** [comment]
Thanks @motiz88. Good shout, let's do this.
