### ISSUE TITLE
Missing configuration key error

### ISSUE THREAD

**Issue by Chr1stian** [FormidableLabs/appr#31]
Hi, would be great if anyone could help me. I have followed all the steps but I get an error when building with Travis.

xxxxx/node_modules/appr/scripts/config.js:20
    throw new Error(`Missing configuration key ${key}`);
    ^
Error: Missing configuration key expUsername

This is the pull request/repo I am working on for reference:
https://github.com/TK-data/it2901-15/pull/18

Thanks!

**Comment by jevakallio** [comment]
@Chr1stian you'll need to set the following Travis environment variables [as described in the readme](https://github.com/FormidableLabs/appr#enable-travis):

 - `EXP_USERNAME` - Exponent username, under which to publish the review apps. Use your main account, or create a new one for review apps. All review apps will be unlisted, so only you can see them in your app listings.
 - `EXP_PASSWORD` - Exponent password for the publish user.
 - `GITHUB_USERNAME` - A user account you want to use for posting the review app links. Use your own, or create a new "bot" account and grant them access to your repo.
 - `GITHUB_TOKEN` - A [Personal API Token](https://github.com/blog/1509-personal-api-tokens) of the user with access to the repository. If the repository is private, the token needs to be granted the full `repo` scope. For public repositories, the `public_repo` scope is enough.

**Comment by Chr1stian** [comment]
Thanks you for extremely fast response. I apparently stopped reading after "Enable Travis", since this was already done on my project. Sorry! and thanks again!

**Comment by jevakallio** [comment]
No worries!
