### ISSUE TITLE
Don't work if set `slug` in app.json

### ISSUE THREAD

**Issue by giautm** [FormidableLabs/appr#7]
`slug` [is required](https://docs.expo.io/versions/v19.0.0/guides/configuration.html#slug) in app.json. 
If i set that field, `appr` don't work anymore. Because if still publish to that slug.

**Comment by tonyxiao** [comment]
Same issue here.

**Comment by giautm** [comment]
@tonyxiao : You can fork and edit as i done to make it work:
https://github.com/FormidableLabs/appr/compare/master...giautm:master

**Comment by tonyxiao** [comment]
Yea I ended up checking that out. Thanks @giautm

**Comment by jevakallio** [comment]
This should now be fixed and released as [v1.1.0](https://github.com/FormidableLabs/appr/releases/tag/v1.1.0). Thanks @giautm and @tonyxiao! 🙇 

I'm closing this issue, please reopen if the issue persists!
