### ISSUE TITLE
Heroku support

### ISSUE THREAD

**Issue by hoebat** [FormidableLabs/appr#9]
Hi there,

I'm a newbie and want to set appr up for heroku pipelines. 

Any advice will be appreciated.

Thanks

**Comment by jevakallio** [comment]
I'm not sure how you'd use appr for heroku pipelines, given that pipelines are used to deploy heroku frontend/backend code.

However, if you have this need, you should be able to implement this using the custom environment variables in your heroku build step: https://github.com/FormidableLabs/appr#configuring-other-cis
